# Generated by Django 4.1.5 on 2023-01-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_nombre_lista_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nombre_lista',
            name='descripcion',
        ),
    ]
